---
title: "Matilda Vignette"
author: "DPM"
date: "2023-07-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(hector)
library(matilda)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
```

# Configure Hector model 

```{r configure-model}
ini <- system.file("input/hector_ssp245.ini", package = "hector")
c_ssp245 <- newcore(ini)
```

# Generate parameter values

```{r generate-params}
set.seed(1)
param_values <- generate_params(c_ssp245, draws = 10)
```

# Run Hector model iteratively 

```{r run-hector, include=FALSE}
results <- iterate_hector(core = c_ssp245,
                          params = param_values)
head(results)
```

# Plot model runs

```{r plot-model-runs}
ggplot(results, aes(x = year, y = value, group = run_number, color = as.factor(run_number))) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y")
```

# Score model runs

```{r score-runs}
scores <- score_hruns(results, criterion_co2_obs(), score_ramp, w1 = 2, w2 = 20)

results_scored <- merge(results, scores, by = "run_number")
```

# Plot scored runs

```{r plot-scored-runs}
ggplot(data = results_scored) +
  geom_line(aes(x = year, y = value, group = run_number, color = weights)) +
  scale_color_continuous() +
  facet_wrap(~variable, scales = "free_y")
```

# Define and calculate metrics

```{r metrics}
my_metric <- new_metric(GLOBAL_TAS(), 2000:2100, mean)

metric_values <- metric_calc(results, my_metric)
```

# Weighted probabilistic projections

```{r projections, include=TRUE}
bins <- c(0, 1, 1.5, 2, 2.5, 3, 3.5, 4, Inf)

prob_calc(metric_values$metric_result, 
          bins = bins, 
          scores = scores$weights)
```
